# Generated by Django 6.0.2 on 2026-02-12 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('server_host', models.CharField(db_index=True, max_length=100)),
                ('metric_type', models.CharField(choices=[('client_open', 'Client Open Count'), ('trapped_time', 'Trapped Time'), ('client_closed', 'Client Closed Count'), ('sent_bytes', 'Sent Bytes')], max_length=50)),
                ('last_sync_at', models.DateTimeField()),
                ('records_synced', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True, default='')),
            ],
            options={
                'indexes': [models.Index(fields=['server_host', 'metric_type'], name='idx_sync_server_metric')],
                'unique_together': {('server_host', 'metric_type')},
            },
        ),
    ]
