# Generated by Django 6.0.2 on 2026-02-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AchievementCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('icon', models.CharField(default='trophy', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Achievement Categories',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_de', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=500)),
                ('description_de', models.TextField(max_length=500)),
                ('metric', models.CharField(choices=[('total_catches', 'Total Catches'), ('total_trapped_seconds', 'Total Trapped Seconds'), ('unique_countries', 'Unique Countries'), ('unique_ips', 'Unique IPs'), ('single_trap_seconds', 'Single Longest Trap'), ('server_catches', 'Catches on Specific Server'), ('species_caught', 'Unique Species Caught'), ('daily_catches', 'Catches in a Single Day'), ('total_bytes_sent', 'Total Bytes Sent')], max_length=50)),
                ('threshold', models.FloatField()),
                ('rarity', models.CharField(choices=[('bronze', 'Bronze'), ('silver', 'Silver'), ('gold', 'Gold'), ('platinum', 'Platinum'), ('diamond', 'Diamond')], max_length=20)),
                ('points', models.PositiveIntegerField(default=10)),
                ('lottie_file', models.CharField(blank=True, default='', max_length=200)),
                ('svg_file', models.CharField(blank=True, default='', max_length=200)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('is_secret', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('server_filter', models.ForeignKey(blank=True, help_text='If set, only counts catches on this server.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquarium.server')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='achievements.achievementcategory')),
            ],
            options={
                'ordering': ['category', 'sort_order'],
            },
        ),
        migrations.CreateModel(
            name='UnlockedAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unlocked_at', models.DateTimeField()),
                ('current_value', models.FloatField()),
                ('notified', models.BooleanField(default=False)),
                ('achievement', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='unlock_record', to='achievements.achievement')),
            ],
            options={
                'ordering': ['-unlocked_at'],
            },
        ),
        migrations.AddIndex(
            model_name='achievement',
            index=models.Index(fields=['metric', 'threshold'], name='idx_achievement_metric'),
        ),
    ]
