# Generated by Django 6.0.2 on 2026-02-12 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('achievements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='metric',
            field=models.CharField(choices=[('total_catches', 'Total Catches'), ('total_trapped_seconds', 'Total Trapped Seconds'), ('unique_countries', 'Unique Countries'), ('unique_ips', 'Unique IPs'), ('single_trap_seconds', 'Single Longest Trap'), ('server_catches', 'Catches on Specific Server'), ('min_server_catches', 'Min Catches Across All Servers'), ('species_caught', 'Unique Species Caught'), ('daily_catches', 'Catches in a Single Day'), ('total_bytes_sent', 'Total Bytes Sent'), ('total_treasures', 'Total Treasures Collected'), ('unique_treasure_types', 'Unique Treasure Types Collected'), ('challenges_completed', 'Total Challenges Completed')], max_length=50),
        ),
    ]
