# Generated by Django 6.0.2 on 2026-02-12 08:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CountryStats',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('country_code', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100)),
                ('total_catches', models.PositiveIntegerField(default=0)),
                ('total_trapped_seconds', models.FloatField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('last_catch_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Country Stats',
                'ordering': ['-total_catches'],
            },
        ),
        migrations.CreateModel(
            name='FishSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('description_de', models.TextField(blank=True, default='', max_length=500)),
                ('min_trapped_seconds', models.PositiveIntegerField()),
                ('max_trapped_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary'), ('mythic', 'Mythic')], max_length=20)),
                ('rarity_color', models.CharField(default='#808080', max_length=7)),
                ('points', models.PositiveIntegerField(default=1)),
                ('lottie_file', models.CharField(blank=True, default='', max_length=200)),
                ('svg_file', models.CharField(blank=True, default='', max_length=200)),
                ('css_class', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Fish Species',
                'ordering': ['sort_order', 'min_trapped_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('host_identifier', models.CharField(db_index=True, max_length=100, unique=True)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('icon', models.CharField(default='server', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('pond_theme', models.CharField(choices=[('ocean', 'Deep Ocean'), ('lake', 'Mountain Lake'), ('reef', 'Coral Reef')], default='ocean', max_length=30)),
                ('total_catches', models.PositiveBigIntegerField(default=0)),
                ('total_trapped_seconds', models.PositiveBigIntegerField(default=0)),
                ('total_bytes_sent', models.PositiveBigIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('unique_countries', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['host_identifier'], name='idx_server_host_id')],
            },
        ),
        migrations.CreateModel(
            name='DailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('new_catches', models.PositiveIntegerField(default=0)),
                ('total_trapped_seconds', models.FloatField(default=0)),
                ('total_bytes_sent', models.PositiveBigIntegerField(default=0)),
                ('unique_ips', models.PositiveIntegerField(default=0)),
                ('unique_countries', models.PositiveIntegerField(default=0)),
                ('top_species_slug', models.SlugField(blank=True, default='')),
                ('longest_trap_seconds', models.FloatField(default=0)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_stats', to='aquarium.server')),
            ],
            options={
                'verbose_name_plural': 'Daily Stats',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['date', 'server'], name='idx_daily_date_server')],
                'unique_together': {('date', 'server')},
            },
        ),
        migrations.CreateModel(
            name='CaughtBot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('ip_hash', models.CharField(db_index=True, max_length=64)),
                ('country_code', models.CharField(blank=True, db_index=True, default='', max_length=2)),
                ('country_name', models.CharField(blank=True, default='', max_length=100)),
                ('geohash', models.CharField(blank=True, default='', max_length=12)),
                ('local_port', models.PositiveIntegerField(default=22)),
                ('trapped_seconds', models.FloatField(default=0)),
                ('bytes_sent', models.PositiveBigIntegerField(default=0)),
                ('first_seen', models.DateTimeField()),
                ('last_seen', models.DateTimeField()),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('connection_count', models.PositiveIntegerField(default=1)),
                ('score', models.PositiveIntegerField(default=0)),
                ('influx_fingerprint', models.CharField(db_index=True, max_length=128, unique=True)),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='catches', to='aquarium.fishspecies')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='catches', to='aquarium.server')),
            ],
            options={
                'ordering': ['-first_seen'],
                'indexes': [models.Index(fields=['server', '-first_seen'], name='idx_catch_server_time'), models.Index(fields=['species', '-trapped_seconds'], name='idx_catch_species_time'), models.Index(fields=['country_code'], name='idx_catch_country'), models.Index(fields=['-score'], name='idx_catch_score'), models.Index(fields=['is_active'], name='idx_catch_active'), models.Index(fields=['ip_hash'], name='idx_catch_ip_hash')],
            },
        ),
    ]
