# Generated by Django 6.0.2 on 2026-02-12 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TreasureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('name_de', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, default='', max_length=500)),
                ('description_de', models.TextField(blank=True, default='', max_length=500)),
                ('emoji', models.CharField(max_length=10)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20)),
                ('rarity_color', models.CharField(default='#808080', max_length=7)),
                ('points', models.PositiveIntegerField(default=5)),
                ('spawn_weight', models.PositiveIntegerField(default=100, help_text='Relative spawn probability. Higher = more likely.')),
                ('min_active_fish', models.PositiveSmallIntegerField(default=1, help_text='Minimum fish in pond for this treasure to spawn.')),
                ('css_class', models.CharField(blank=True, default='', max_length=50)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Treasure Types',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ChallengeTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('name_de', models.CharField(max_length=200)),
                ('description_template', models.CharField(help_text='Template string with {threshold} placeholder.', max_length=300)),
                ('description_template_de', models.CharField(help_text='German template string with {threshold} placeholder.', max_length=300)),
                ('metric', models.CharField(choices=[('daily_catches', 'Catches Today'), ('daily_trapped_seconds', 'Trapped Seconds Today'), ('daily_unique_countries', 'Unique Countries Today'), ('daily_unique_species', 'Unique Species Today'), ('daily_rare_catches', 'Rare+ Catches Today'), ('daily_treasures', 'Treasures Collected Today')], max_length=50)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=20)),
                ('threshold_min', models.PositiveIntegerField()),
                ('threshold_max', models.PositiveIntegerField()),
                ('reward_points', models.PositiveIntegerField(default=25)),
                ('emoji', models.CharField(default='🎯', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('server_filter', models.ForeignKey(blank=True, help_text='If set, challenge only counts catches on this server.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='aquarium.server')),
            ],
            options={
                'ordering': ['difficulty', 'slug'],
            },
        ),
        migrations.CreateModel(
            name='DailyChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(db_index=True)),
                ('threshold', models.PositiveIntegerField()),
                ('description', models.CharField(max_length=300)),
                ('description_de', models.CharField(max_length=300)),
                ('reward_points', models.PositiveIntegerField()),
                ('current_value', models.FloatField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notified', models.BooleanField(default=False)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='aquarium.challengetemplate')),
            ],
            options={
                'ordering': ['-date', 'template__difficulty'],
                'indexes': [models.Index(fields=['date', 'is_completed'], name='idx_challenge_date_done')],
                'unique_together': {('date', 'template')},
            },
        ),
        migrations.CreateModel(
            name='CollectedTreasure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pond_treasure_id', models.CharField(db_index=True, help_text='UUID of the treasure instance in the pond.', max_length=64, unique=True)),
                ('collected_at', models.DateTimeField()),
                ('active_fish_count', models.PositiveSmallIntegerField(default=0)),
                ('points_awarded', models.PositiveIntegerField(default=0)),
                ('treasure_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='aquarium.treasuretype')),
            ],
            options={
                'ordering': ['-collected_at'],
                'indexes': [models.Index(fields=['-collected_at'], name='idx_treasure_collected')],
            },
        ),
    ]
