# Generated by Django 6.0.2 on 2026-02-12 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0002_treasuretype_challengetemplate_dailychallenge_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityTip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('title_de', models.CharField(max_length=200)),
                ('content_de', models.TextField(max_length=2000)),
                ('source_url', models.URLField(blank=True, default='', max_length=500)),
                ('source_label', models.CharField(blank=True, default='', max_length=200)),
                ('rarity', models.CharField(choices=[('common', 'Common'), ('uncommon', 'Uncommon'), ('rare', 'Rare'), ('epic', 'Epic'), ('legendary', 'Legendary')], max_length=20)),
                ('category', models.CharField(choices=[('ssh', 'SSH'), ('firewall', 'Firewall'), ('monitoring', 'Monitoring'), ('auth', 'Authentication'), ('updates', 'Updates'), ('network', 'Network'), ('container', 'Container'), ('strategy', 'Strategy')], max_length=30)),
                ('emoji', models.CharField(default='🔒', max_length=10)),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'ordering': ['rarity', 'sort_order'],
            },
        ),
        migrations.AddField(
            model_name='collectedtreasure',
            name='security_tip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tip_collections', to='aquarium.securitytip'),
        ),
    ]
