# Generated by Django 6.0.2 on 2026-02-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0003_securitytip_collectedtreasure_security_tip'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitytip',
            name='content',
            field=models.TextField(default='', max_length=2000),
        ),
        migrations.AddField(
            model_name='securitytip',
            name='source_label_de',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
