# Generated by Django 6.0.2 on 2026-02-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0004_add_security_tip_bilingual_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPLookupLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ip_address', models.GenericIPAddressField(unique=True)),
                ('abuse_score', models.PositiveSmallIntegerField(default=0)),
                ('is_tor', models.BooleanField(default=False)),
                ('has_vulns', models.BooleanField(default=False)),
                ('has_dangerous_ports', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'IP Lookup Log',
            },
        ),
    ]
