# Generated by Django 6.0.2 on 2026-02-14 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0005_add_ip_lookup_log'),
    ]

    operations = [
        migrations.RenameField(
            model_name='treasuretype',
            old_name='min_active_fish',
            new_name='min_pond_percentile',
        ),
        migrations.AlterField(
            model_name='treasuretype',
            name='min_pond_percentile',
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text='Minimum pond activity percentile (0-100) for this treasure to spawn.',
            ),
        ),
    ]
