# Generated by Django 6.0.2 on 2026-02-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0006_rename_min_active_fish_to_min_pond_percentile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='securitytip',
            options={'ordering': ['tip_type', 'sort_order']},
        ),
        migrations.AddField(
            model_name='securitytip',
            name='tip_type',
            field=models.CharField(choices=[('security', 'Security Tip'), ('fun_fact', 'Fun Fact'), ('humor', 'Humor'), ('article', 'Article Link'), ('promo', 'Project Promo')], db_index=True, default='security', max_length=20),
        ),
        migrations.AddField(
            model_name='treasuretype',
            name='preferred_tip_types',
            field=models.CharField(blank=True, default='', help_text="Comma-separated tip_types (e.g. 'article,promo'). Empty = security,fun_fact,humor.", max_length=100),
        ),
        migrations.AlterField(
            model_name='securitytip',
            name='category',
            field=models.CharField(choices=[('ssh', 'SSH'), ('firewall', 'Firewall'), ('monitoring', 'Monitoring'), ('auth', 'Authentication'), ('updates', 'Updates'), ('network', 'Network'), ('container', 'Container'), ('strategy', 'Strategy'), ('fun', 'Fun & Humor'), ('article', 'Article'), ('promo', 'Promotion')], max_length=30),
        ),
    ]
