# Generated by Django 6.0.2 on 2026-03-27 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aquarium', '0007_alter_securitytip_options_securitytip_tip_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caughtbot',
            name='geohash',
            field=models.CharField(blank=True, default='', max_length=24),
        ),
    ]
