"""Seed data for fish species and servers. Used by data migrations."""

FISH_SPECIES = [
    {
        "slug": "plankton",
        "name": "Plankton",
        "name_de": "Plankton",
        "description": "Barely a blip on the radar. Gone before you noticed.",
        "description_de": "Kaum ein Blip auf dem Radar. Weg, bevor du es bemerkst.",
        "min_trapped_seconds": 0,
        "max_trapped_seconds": 10,
        "rarity": "common",
        "rarity_color": "#9CA3AF",
        "points": 1,
        "css_class": "fish-plankton",
        "sort_order": 1,
    },
    {
        "slug": "sardine",
        "name": "Sardine",
        "name_de": "Sardine",
        "description": "A tiny catch, but every fisher starts somewhere.",
        "description_de": "Ein winziger Fang, aber jeder Angler fängt mal klein an.",
        "min_trapped_seconds": 10,
        "max_trapped_seconds": 60,
        "rarity": "common",
        "rarity_color": "#60A5FA",
        "points": 2,
        "css_class": "fish-sardine",
        "sort_order": 2,
    },
    {
        "slug": "anchovy",
        "name": "Anchovy",
        "name_de": "Anchovis",
        "description": "Small but feisty. Took the bait and struggled a bit.",
        "description_de": "Klein aber zappelig. Hat angebissen und etwas gekämpft.",
        "min_trapped_seconds": 60,
        "max_trapped_seconds": 300,
        "rarity": "common",
        "rarity_color": "#34D399",
        "points": 5,
        "css_class": "fish-anchovy",
        "sort_order": 3,
    },
    {
        "slug": "trout",
        "name": "Rainbow Trout",
        "name_de": "Regenbogenforelle",
        "description": "A respectable catch! This one put up a decent fight.",
        "description_de": "Ein respektabler Fang! Dieser hat ordentlich gekämpft.",
        "min_trapped_seconds": 300,
        "max_trapped_seconds": 900,
        "rarity": "uncommon",
        "rarity_color": "#A78BFA",
        "points": 10,
        "css_class": "fish-trout",
        "sort_order": 4,
    },
    {
        "slug": "pike",
        "name": "Northern Pike",
        "name_de": "Hecht",
        "description": "The predator became the prey. A satisfying reversal.",
        "description_de": "Der Räuber wurde zur Beute. Eine befriedigende Wendung.",
        "min_trapped_seconds": 900,
        "max_trapped_seconds": 1800,
        "rarity": "uncommon",
        "rarity_color": "#F472B6",
        "points": 20,
        "css_class": "fish-pike",
        "sort_order": 5,
    },
    {
        "slug": "salmon",
        "name": "Atlantic Salmon",
        "name_de": "Atlantischer Lachs",
        "description": "A prized catch! Half an hour of wasted bot resources.",
        "description_de": "Ein Prachtfang! Eine halbe Stunde verschwendete Bot-Ressourcen.",
        "min_trapped_seconds": 1800,
        "max_trapped_seconds": 3600,
        "rarity": "rare",
        "rarity_color": "#FB923C",
        "points": 50,
        "css_class": "fish-salmon",
        "sort_order": 6,
    },
    {
        "slug": "tuna",
        "name": "Bluefin Tuna",
        "name_de": "Roter Thun",
        "description": "Hours of trapped time. This bot's operator is losing money.",
        "description_de": "Stunden in der Falle. Dieser Bot-Betreiber verliert Geld.",
        "min_trapped_seconds": 3600,
        "max_trapped_seconds": 14400,
        "rarity": "rare",
        "rarity_color": "#F87171",
        "points": 100,
        "css_class": "fish-tuna",
        "sort_order": 7,
    },
    {
        "slug": "swordfish",
        "name": "Swordfish",
        "name_de": "Schwertfisch",
        "description": "A majestic beast! Half a day trapped in our net.",
        "description_de": "Ein majestätisches Biest! Einen halben Tag in unserem Netz.",
        "min_trapped_seconds": 14400,
        "max_trapped_seconds": 43200,
        "rarity": "epic",
        "rarity_color": "#FBBF24",
        "points": 250,
        "css_class": "fish-swordfish",
        "sort_order": 8,
    },
    {
        "slug": "marlin",
        "name": "Blue Marlin",
        "name_de": "Blauer Marlin",
        "description": "The stuff of legends! A full day wasted on our tarpit.",
        "description_de": "Der Stoff aus dem Legenden sind! Ein ganzer Tag in unserem Tarpit.",
        "min_trapped_seconds": 43200,
        "max_trapped_seconds": 86400,
        "rarity": "epic",
        "rarity_color": "#818CF8",
        "points": 500,
        "css_class": "fish-marlin",
        "sort_order": 9,
    },
    {
        "slug": "whale-shark",
        "name": "Whale Shark",
        "name_de": "Walhai",
        "description": "Incredible! Days of trapped time. The bot forgot it exists.",
        "description_de": "Unglaublich! Tage in der Falle. Der Bot hat vergessen, dass er existiert.",
        "min_trapped_seconds": 86400,
        "max_trapped_seconds": 259200,
        "rarity": "legendary",
        "rarity_color": "#2DD4BF",
        "points": 1000,
        "css_class": "fish-whale-shark",
        "sort_order": 10,
    },
    {
        "slug": "kraken",
        "name": "Kraken",
        "name_de": "Kraken",
        "description": "A mythical creature from the deep! A week of wasted compute.",
        "description_de": "Ein mythisches Wesen aus der Tiefe! Eine Woche verschwendete Rechenzeit.",
        "min_trapped_seconds": 259200,
        "max_trapped_seconds": 604800,
        "rarity": "legendary",
        "rarity_color": "#E879F9",
        "points": 2500,
        "css_class": "fish-kraken",
        "sort_order": 11,
    },
    {
        "slug": "leviathan",
        "name": "Leviathan",
        "name_de": "Leviathan",
        "description": "THE ULTIMATE CATCH. Over a week trapped. This bot is never coming back.",
        "description_de": "DER ULTIMATIVE FANG. Über eine Woche gefangen. Dieser Bot kommt nie wieder.",
        "min_trapped_seconds": 604800,
        "max_trapped_seconds": None,
        "rarity": "mythic",
        "rarity_color": "#FF0040",
        "points": 5000,
        "css_class": "fish-leviathan",
        "sort_order": 12,
    },
]

SERVERS = [
    {
        "slug": "rs-cronwolf",
        "name": "RS Cronwolf",
        "host_identifier": "rs-cronwolf",
        "description": "The main fishing pond. Deep waters, heavy traffic.",
        "pond_theme": "ocean",
    },
    {
        "slug": "vps-netcup",
        "name": "VPS Netcup",
        "host_identifier": "vps-netcup",
        "description": "Mountain lake outpost. Netcup territory.",
        "pond_theme": "lake",
    },
    {
        "slug": "vps2",
        "name": "VPS2",
        "host_identifier": "vps2-statuspage",
        "description": "Coral reef station. Neighbor of Netcup.",
        "pond_theme": "reef",
    },
]

ACHIEVEMENT_CATEGORIES = [
    {
        "slug": "first-steps",
        "name": "First Steps",
        "name_de": "Erste Schritte",
        "icon": "footprints",
        "sort_order": 1,
    },
    {
        "slug": "time-waster",
        "name": "Time Waster",
        "name_de": "Zeitverschwender",
        "icon": "clock",
        "sort_order": 2,
    },
    {
        "slug": "patience",
        "name": "Patience is a Virtue",
        "name_de": "Geduld ist eine Tugend",
        "icon": "hourglass",
        "sort_order": 3,
    },
    {
        "slug": "traveler",
        "name": "World Traveler",
        "name_de": "Weltreisender",
        "icon": "globe",
        "sort_order": 4,
    },
    {
        "slug": "collector",
        "name": "Collector",
        "name_de": "Sammler",
        "icon": "collection",
        "sort_order": 5,
    },
    {
        "slug": "server-master",
        "name": "Server Master",
        "name_de": "Server-Meister",
        "icon": "server",
        "sort_order": 6,
    },
    {
        "slug": "data-hoarder",
        "name": "Data Hoarder",
        "name_de": "Datenhamster",
        "icon": "database",
        "sort_order": 7,
    },
]

ACHIEVEMENTS = [
    # First Steps - total catches
    {"slug": "first-catch", "category": "first-steps", "name": "First Catch", "name_de": "Erster Fang",
     "description": "Catch your first bot.", "description_de": "Fange deinen ersten Bot.",
     "metric": "total_catches", "threshold": 1, "rarity": "bronze", "points": 10, "sort_order": 1},
    {"slug": "ten-catches", "category": "first-steps", "name": "Getting Started", "name_de": "Es geht los",
     "description": "Catch 10 bots.", "description_de": "Fange 10 Bots.",
     "metric": "total_catches", "threshold": 10, "rarity": "bronze", "points": 25, "sort_order": 2},
    {"slug": "hundred-catches", "category": "first-steps", "name": "Century", "name_de": "Jahrhundert",
     "description": "Catch 100 bots.", "description_de": "Fange 100 Bots.",
     "metric": "total_catches", "threshold": 100, "rarity": "silver", "points": 50, "sort_order": 3},
    {"slug": "thousand-catches", "category": "first-steps", "name": "Kilocatch", "name_de": "Kilofang",
     "description": "Catch 1,000 bots.", "description_de": "Fange 1.000 Bots.",
     "metric": "total_catches", "threshold": 1000, "rarity": "gold", "points": 100, "sort_order": 4},
    {"slug": "ten-thousand-catches", "category": "first-steps", "name": "Bot Slayer", "name_de": "Bot-Jäger",
     "description": "Catch 10,000 bots.", "description_de": "Fange 10.000 Bots.",
     "metric": "total_catches", "threshold": 10000, "rarity": "platinum", "points": 250, "sort_order": 5},
    {"slug": "hundred-thousand-catches", "category": "first-steps", "name": "Bot Apocalypse", "name_de": "Bot-Apokalypse",
     "description": "Catch 100,000 bots.", "description_de": "Fange 100.000 Bots.",
     "metric": "total_catches", "threshold": 100000, "rarity": "diamond", "points": 500, "sort_order": 6},
    # Time Waster - total trapped seconds
    {"slug": "one-hour-wasted", "category": "time-waster", "name": "Coffee Break", "name_de": "Kaffeepause",
     "description": "Waste 1 hour of bot time.", "description_de": "Verschwende 1 Stunde Bot-Zeit.",
     "metric": "total_trapped_seconds", "threshold": 3600, "rarity": "bronze", "points": 25, "sort_order": 1},
    {"slug": "eight-hours-wasted", "category": "time-waster", "name": "Work Day", "name_de": "Arbeitstag",
     "description": "Waste 8 hours of bot time.", "description_de": "Verschwende 8 Stunden Bot-Zeit.",
     "metric": "total_trapped_seconds", "threshold": 28800, "rarity": "silver", "points": 50, "sort_order": 2},
    {"slug": "seven-days-wasted", "category": "time-waster", "name": "Week Wrecker", "name_de": "Wochen-Vernichter",
     "description": "Waste 7 days of bot time.", "description_de": "Verschwende 7 Tage Bot-Zeit.",
     "metric": "total_trapped_seconds", "threshold": 604800, "rarity": "gold", "points": 100, "sort_order": 3},
    {"slug": "thirty-days-wasted", "category": "time-waster", "name": "Month Muncher", "name_de": "Monats-Fresser",
     "description": "Waste 30 days of bot time.", "description_de": "Verschwende 30 Tage Bot-Zeit.",
     "metric": "total_trapped_seconds", "threshold": 2592000, "rarity": "platinum", "points": 250, "sort_order": 4},
    {"slug": "year-wasted", "category": "time-waster", "name": "Time Lord", "name_de": "Zeitherrscher",
     "description": "Waste 365 days of bot time.", "description_de": "Verschwende 365 Tage Bot-Zeit.",
     "metric": "total_trapped_seconds", "threshold": 31536000, "rarity": "diamond", "points": 500, "sort_order": 5},
    # Patience - single longest trap
    {"slug": "one-minute-trap", "category": "patience", "name": "Patience Test", "name_de": "Geduldsprobe",
     "description": "Trap a single bot for 1 minute.", "description_de": "Halte einen einzelnen Bot 1 Minute fest.",
     "metric": "single_trap_seconds", "threshold": 60, "rarity": "bronze", "points": 15, "sort_order": 1},
    {"slug": "one-hour-trap", "category": "patience", "name": "Iron Will", "name_de": "Eiserner Wille",
     "description": "Trap a single bot for 1 hour.", "description_de": "Halte einen einzelnen Bot 1 Stunde fest.",
     "metric": "single_trap_seconds", "threshold": 3600, "rarity": "silver", "points": 50, "sort_order": 2},
    {"slug": "one-day-trap", "category": "patience", "name": "Day Keeper", "name_de": "Tageswächter",
     "description": "Trap a single bot for 24 hours.", "description_de": "Halte einen einzelnen Bot 24 Stunden fest.",
     "metric": "single_trap_seconds", "threshold": 86400, "rarity": "gold", "points": 150, "sort_order": 3},
    {"slug": "one-week-trap", "category": "patience", "name": "Eternal Guardian", "name_de": "Ewiger Wächter",
     "description": "Trap a single bot for 7 days.", "description_de": "Halte einen einzelnen Bot 7 Tage fest.",
     "metric": "single_trap_seconds", "threshold": 604800, "rarity": "diamond", "points": 500, "sort_order": 4},
    # World Traveler - unique countries
    {"slug": "first-country", "category": "traveler", "name": "Local Fisher", "name_de": "Lokaler Angler",
     "description": "Catch bots from 1 country.", "description_de": "Fange Bots aus 1 Land.",
     "metric": "unique_countries", "threshold": 1, "rarity": "bronze", "points": 10, "sort_order": 1},
    {"slug": "ten-countries", "category": "traveler", "name": "Continental", "name_de": "Kontinental",
     "description": "Catch bots from 10 countries.", "description_de": "Fange Bots aus 10 Ländern.",
     "metric": "unique_countries", "threshold": 10, "rarity": "silver", "points": 50, "sort_order": 2},
    {"slug": "thirty-countries", "category": "traveler", "name": "Globetrotter", "name_de": "Globetrotter",
     "description": "Catch bots from 30 countries.", "description_de": "Fange Bots aus 30 Ländern.",
     "metric": "unique_countries", "threshold": 30, "rarity": "gold", "points": 100, "sort_order": 3},
    {"slug": "fifty-countries", "category": "traveler", "name": "World Fisher", "name_de": "Weltangler",
     "description": "Catch bots from 50 countries.", "description_de": "Fange Bots aus 50 Ländern.",
     "metric": "unique_countries", "threshold": 50, "rarity": "platinum", "points": 200, "sort_order": 4},
    {"slug": "hundred-countries", "category": "traveler", "name": "Pangaea Fisher", "name_de": "Pangäa-Angler",
     "description": "Catch bots from 100 countries.", "description_de": "Fange Bots aus 100 Ländern.",
     "metric": "unique_countries", "threshold": 100, "rarity": "diamond", "points": 500, "sort_order": 5},
    # Collector - unique species caught
    {"slug": "three-species", "category": "collector", "name": "Beginner's Net", "name_de": "Anfänger-Netz",
     "description": "Catch 3 different fish species.", "description_de": "Fange 3 verschiedene Fischarten.",
     "metric": "species_caught", "threshold": 3, "rarity": "bronze", "points": 25, "sort_order": 1},
    {"slug": "six-species", "category": "collector", "name": "Diverse Catch", "name_de": "Vielfältiger Fang",
     "description": "Catch 6 different fish species.", "description_de": "Fange 6 verschiedene Fischarten.",
     "metric": "species_caught", "threshold": 6, "rarity": "silver", "points": 75, "sort_order": 2},
    {"slug": "nine-species", "category": "collector", "name": "Master Angler", "name_de": "Meisterangler",
     "description": "Catch 9 different fish species.", "description_de": "Fange 9 verschiedene Fischarten.",
     "metric": "species_caught", "threshold": 9, "rarity": "gold", "points": 150, "sort_order": 3},
    {"slug": "all-species", "category": "collector", "name": "Complete Collection", "name_de": "Vollständige Sammlung",
     "description": "Catch all 12 fish species!", "description_de": "Fange alle 12 Fischarten!",
     "metric": "species_caught", "threshold": 12, "rarity": "diamond", "points": 500, "sort_order": 4},
    # Data Hoarder - total bytes sent
    {"slug": "one-kb-sent", "category": "data-hoarder", "name": "Byte Bite", "name_de": "Byte-Häppchen",
     "description": "Send 1 KB of tarpit data.", "description_de": "Sende 1 KB Tarpit-Daten.",
     "metric": "total_bytes_sent", "threshold": 1024, "rarity": "bronze", "points": 10, "sort_order": 1},
    {"slug": "one-mb-sent", "category": "data-hoarder", "name": "Mega Fisher", "name_de": "Mega-Angler",
     "description": "Send 1 MB of tarpit data.", "description_de": "Sende 1 MB Tarpit-Daten.",
     "metric": "total_bytes_sent", "threshold": 1048576, "rarity": "silver", "points": 50, "sort_order": 2},
    {"slug": "one-gb-sent", "category": "data-hoarder", "name": "Giga Chad Fisher", "name_de": "Giga-Chad-Angler",
     "description": "Send 1 GB of tarpit data.", "description_de": "Sende 1 GB Tarpit-Daten.",
     "metric": "total_bytes_sent", "threshold": 1073741824, "rarity": "diamond", "points": 500, "sort_order": 3},
]
