# Generated by Django 6.0.2 on 2026-02-15 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_backfill_achievements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('achievement', 'Achievement Unlocked'), ('challenge', 'Daily Challenge Completed'), ('rare_catch', 'Rare Fish Caught'), ('treasure', 'Treasure Tip Discovered')], db_index=True, max_length=20),
        ),
    ]
